### PR TITLE
Replace all `neighbours` with `neighbors`

### PR DESCRIPTION
**Pull request by maksymiuks**
Candidate fix for #364. All `neighbours` entries in the source were removed and replaced with `neighbor`. Solution tested with grep.

### CODE REVIEW

**Comment by hbaniecki** [comment]
Btw. in EMA there is `neighbours` everywhere in text.

**Comment by pbiecek** [comment]
@hbaniecki thanks, actually this was the reason for this change
in the online version of EMA it is inconsistent but will be corrected. 
in the printed version we use US spelling

**Comment by hbaniecki** [comment]
I believe that `predict_diagnostics` returns an error when `data` has less than `50` observations. This could be easily fixed in this PR.

**Comment by maksymiuks** [comment]
fixed in https://github.com/ModelOriented/DALEX/pull/369/commits/f5e473b8b1726772bce89b183590766cc0710014

**Review by pbiecek — CHANGES_REQUESTED** [review]
looks great
please update NEWS.md and bump version +0.0.1

**Comment by pbiecek** [comment]
Thanks!

**Pull request merged**
