### PR TITLE
added some suggestions to vignette

### PR DESCRIPTION
**Pull request by kasiapekala**
added some suggestions to vignette about multilabel classification

### CODE REVIEW

**Review by maksymiuks — APPROVED** [review]
I would remove survival word from the title. Besides it looks great.

**Comment by maksymiuks** [comment]
Looks great for me. Should i merge? @pbiecek

**Comment by kasiapekala** [comment]
> 
> 
> I would remove survival word from the title. Besides it looks great.

Replaced "survival" with "example".

**Comment by pbiecek** [comment]
thanks, looks great

**Pull request merged**
