### PR TITLE
[Pyton][Arena] Add Fairnes plot

### PR DESCRIPTION
**Pull request by piotrpiatyszek**
Adds Fairness Check to Arena module.
Example usage is in notebook https://gist.github.com/piotrpiatyszek/86f3eb5d749c6a9dabcf75ab7f325917

### CODE REVIEW

**Review by hbaniecki — CHANGES_REQUESTED** [review]
Looks good to me. Could you add a notice about new feature to `NEWS.md`?

**Comment by hbaniecki** [comment]
mentions #368

**Review by jakwisn — APPROVED** [review]
Checked it also on `german` and other models, seems ok. Great job

**Review by hbaniecki — APPROVED** [review]
thanks

**Pull request merged**
